### PR TITLE
Add Accommodation model

### LINKED ISSUE #1: Add accommodation model
Add a model for accommodations, which should inherit all attributes of points of interest plus the following attributes:

- institution (Träger) - possibly foreign key to organization
- rules of the accommodation

- information about beds can be obtained by a reverse foreign key from the beds model.

### PR DESCRIPTION
**Pull request by tailoric**
Adds the accommodation model and makes it creatable in the admin page

Feedback needed:

- should institution be an account or other model or is a name enough?
- how should the translations of the rules be handled (should this be done with a subclass of POITranslations or just extend POITranslations?)
- should the rules something different?

Closes #1

### CODE REVIEW

**Comment by timobrembeck** [comment]
Just a small side note: I suggest outsourcing the model to a new file `accommodation.py` in the models directory.

**Review by timobrembeck — DISMISSED** [review]
Looks perfectly fine, thank you! :rocket: 
Would you mind if I rebased the branch and combined some of the commits before merging? Atomic commits are perfect when developing a feature on its own branch, but once we merge it into the develop-branch, we could omit commits which didn't end up in the final feature (e.g. the Bed model)...

**Comment by tailoric** [comment]
This is all already pushed should I do a force push then if I rebase or should I put this on another branch and commit that one?

**Comment by tailoric** [comment]
oh wait I misread, you wanted to do the rebasing

I don't mind that, go ahead

**Review by timobrembeck — APPROVED** [review]

**Pull request merged**
